/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperControl9xA3pRouteImport } from './routes/super-control-9xA3p'
import { Route as IndexRouteImport } from './routes/index'

const SuperControl9xA3pRoute = SuperControl9xA3pRouteImport.update({
  id: '/super-control-9xA3p',
  path: '/super-control-9xA3p',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/super-control-9xA3p': typeof SuperControl9xA3pRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/super-control-9xA3p': typeof SuperControl9xA3pRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/super-control-9xA3p': typeof SuperControl9xA3pRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/super-control-9xA3p'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/super-control-9xA3p'
  id: '__root__' | '/' | '/super-control-9xA3p'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperControl9xA3pRoute: typeof SuperControl9xA3pRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-control-9xA3p': {
      id: '/super-control-9xA3p'
      path: '/super-control-9xA3p'
      fullPath: '/super-control-9xA3p'
      preLoaderRoute: typeof SuperControl9xA3pRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperControl9xA3pRoute: SuperControl9xA3pRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
